UPDATE READ.md 各テストケースに具体的な入力値、期待値を明示
SLStudioLesson/chapter3assessment pull request #2
Opened 2024-03-29 10:57 UTC by kkaintover

`README.md`にて設問5,6,7のテストケースに具体的な入力値と期待値を指示
チケット:https://www.notion.so/19db2180b13548448b51cb79f6ee49c3?pvs=4

2024-04-01 05:43 UTC, yugo-mizuochi requested changes

2024-04-01 05:43 UTC, yugo-mizuochi commented on README.md
> +- コンソールにメインメニューが表示されている時、 "1" を入力すると以下の出力が表示されることを確認します。
前提条件として、その前のファイル形式選択メニューにて「1. CSV」を選択するという手順も追記お願いします

2024-04-01 05:43 UTC, yugo-mizuochi commented on README.md
> +- コンソールにメインメニューが表示されている時 "2" を入力後、入力以下入出力例通りにレシピ名と主な材料を入力した場合、入力完了後に `"Recipe added successfully."` というメッセージが表示されることを確認します。
ここも前提条件として、その前のファイル形式選択メニューにて「1. CSV」を選択するという手順も追記お願いします

2024-04-01 05:43 UTC, yugo-mizuochi commented on README.md
> +- コンソールにメインメニューが表示されている時 "3" を入力後、検索クエリ`name=Soup&ingredient=Tomato`を入力した場合、以下入出力例通りに条件に一致するレシピが表示されることを確認します。
ここも前提条件として、その前のファイル形式選択メニューにて「1. CSV」を選択するという手順も追記お願いします

2024-04-01 05:43 UTC, yugo-mizuochi commented on README.md
> +- コンソールにメインメニューが表示されている時 "3" を入力後、検索クエリ`name=Pizza`を入力し、以下入出力例通りに`No matching recipes found.`というメッセージが表示されることを確認します。
ここも前提条件として、その前のファイル形式選択メニューにて「1. CSV」を選択するという手順も追記お願いします

2024-04-01 05:43 UTC, yugo-mizuochi commented on README.md
> +- `recipes.csv`ファイルの内容を全て削除した後、テストケース1の手順を行った場合に以下のメッセージがコンソールに表示された後、メインメニューのことを確認します。
```suggestion
- `recipes.csv`ファイルの内容を全て削除した後、テストケース1の手順を行った場合に以下のメッセージがコンソールに表示された後、メインメニューが表示されることを確認します。
```
「メインメニューのことを確認します」とは？となりました。

2024-04-01 09:50 UTC, kkaintover commented on README.md
> +- コンソールにメインメニューが表示されている時、 "1" を入力すると以下の出力が表示されることを確認します。
以下の文言を追加しました。
```
ファイル形式選択メニューで 「1.CSV」 を選択します。
```

2024-04-01 09:50 UTC, kkaintover commented on README.md
> +- コンソールにメインメニューが表示されている時 "2" を入力後、入力以下入出力例通りにレシピ名と主な材料を入力した場合、入力完了後に `"Recipe added successfully."` というメッセージが表示されることを確認します。
こちらも以下の文言を追加しました。
```
ファイル形式選択メニューで 「1.CSV」 を選択します。
```

2024-04-01 09:51 UTC, kkaintover commented on README.md
> +- コンソールにメインメニューが表示されている時 "3" を入力後、検索クエリ`name=Soup&ingredient=Tomato`を入力した場合、以下入出力例通りに条件に一致するレシピが表示されることを確認します。
こちらも以下の文言を追加しました。
```
ファイル形式選択メニューで 「1.CSV」 を選択します。
```

2024-04-01 09:51 UTC, kkaintover commented on README.md
> +- コンソールにメインメニューが表示されている時 "3" を入力後、検索クエリ`name=Pizza`を入力し、以下入出力例通りに`No matching recipes found.`というメッセージが表示されることを確認します。
こちらも以下の文言を追加しました。
```
ファイル形式選択メニューで 「1.CSV」 を選択します。
```

2024-04-01 09:58 UTC, kkaintover commented on README.md
> +- `recipes.csv`ファイルの内容を全て削除した後、テストケース1の手順を行った場合に以下のメッセージがコンソールに表示された後、メインメニューのことを確認します。
以下の通り修正しました
```
`recipes.csv`ファイルの内容を全て削除した後、テストケース1の手順を行った場合に以下のメッセージがコンソールに表示された後、メインメニューが表示されることを確認します。
```

2024-04-02 00:36 UTC, yugo-mizuochi approved these changes

2024-04-08 08:18 UTC, merged